server:
  port: 8080

spring:
  application:
    name: api-monitoring-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

opensearch:
  host: ${OPENSEARCH_HOST:opensearch}
  port: ${OPENSEARCH_PORT:9200}
  scheme: http
  username: ""
  password: ""

python:
  service:
    url: http://ml-models:8000

logging:
  pattern:
    level: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

fluentd:
  host: fluentd
  port: 9880
  path: /api-logs.${spring.application.name}

flyway:
  enabled: false